name: CI

on:
  push:
    branches: [ "acceptable" ]
  pull_request:
    branches: [ "acceptable" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux
    steps:
      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --needed --noconfirm sdl2 sdl2_ttf

      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: mlugg/setup-zig@v1
        with:
          version: 0.14.0

      - name: Check, test, build
        run: |
          zig fmt --check .
          zig build test
          zig build -Doptimize=ReleaseSafe
